// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: regtest/regtest.proto

package registry

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A base message to be extended
type BaseMessage struct {
	state           protoimpl.MessageState
	sizeCache       protoimpl.SizeCache
	unknownFields   protoimpl.UnknownFields
	extensionFields protoimpl.ExtensionFields

	Bf1 *string `protobuf:"bytes,1,opt,name=bf1" json:"bf1,omitempty"`
}

func (x *BaseMessage) Reset() {
	*x = BaseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_regtest_regtest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseMessage) ProtoMessage() {}

func (x *BaseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_regtest_regtest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseMessage.ProtoReflect.Descriptor instead.
func (*BaseMessage) Descriptor() ([]byte, []int) {
	return file_regtest_regtest_proto_rawDescGZIP(), []int{0}
}

func (x *BaseMessage) GetBf1() string {
	if x != nil && x.Bf1 != nil {
		return *x.Bf1
	}
	return ""
}

// A message scope for more extensions
type ExtensionMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Emf1 *string `protobuf:"bytes,1,opt,name=emf1" json:"emf1,omitempty"`
}

func (x *ExtensionMessage) Reset() {
	*x = ExtensionMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_regtest_regtest_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtensionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionMessage) ProtoMessage() {}

func (x *ExtensionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_regtest_regtest_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionMessage.ProtoReflect.Descriptor instead.
func (*ExtensionMessage) Descriptor() ([]byte, []int) {
	return file_regtest_regtest_proto_rawDescGZIP(), []int{1}
}

func (x *ExtensionMessage) GetEmf1() string {
	if x != nil && x.Emf1 != nil {
		return *x.Emf1
	}
	return ""
}

type ExtensionMessage_NestedExtension struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nef1 *string `protobuf:"bytes,1,opt,name=nef1" json:"nef1,omitempty"`
}

func (x *ExtensionMessage_NestedExtension) Reset() {
	*x = ExtensionMessage_NestedExtension{}
	if protoimpl.UnsafeEnabled {
		mi := &file_regtest_regtest_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtensionMessage_NestedExtension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionMessage_NestedExtension) ProtoMessage() {}

func (x *ExtensionMessage_NestedExtension) ProtoReflect() protoreflect.Message {
	mi := &file_regtest_regtest_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionMessage_NestedExtension.ProtoReflect.Descriptor instead.
func (*ExtensionMessage_NestedExtension) Descriptor() ([]byte, []int) {
	return file_regtest_regtest_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ExtensionMessage_NestedExtension) GetNef1() string {
	if x != nil && x.Nef1 != nil {
		return *x.Nef1
	}
	return ""
}

var file_regtest_regtest_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*BaseMessage)(nil),
		ExtensionType: (*string)(nil),
		Field:         1000,
		Name:          "regtest.ef1",
		Tag:           "bytes,1000,opt,name=ef1",
		Filename:      "regtest/regtest.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*BaseMessage)(nil),
		Field:         56789,
		Name:          "regtest.base",
		Tag:           "bytes,56789,opt,name=base",
		Filename:      "regtest/regtest.proto",
	},
	{
		ExtendedType:  (*BaseMessage)(nil),
		ExtensionType: (*ExtensionMessage)(nil),
		Field:         1001,
		Name:          "regtest.ExtensionMessage.ef2",
		Tag:           "bytes,1001,opt,name=ef2",
		Filename:      "regtest/regtest.proto",
	},
	{
		ExtendedType:  (*BaseMessage)(nil),
		ExtensionType: (*string)(nil),
		Field:         1002,
		Name:          "regtest.ExtensionMessage.NestedExtension.ef3",
		Tag:           "bytes,1002,opt,name=ef3",
		Filename:      "regtest/regtest.proto",
	},
}

// Extension fields to BaseMessage.
var (
	// optional string ef1 = 1000;
	E_Ef1 = &file_regtest_regtest_proto_extTypes[0]
	// optional regtest.ExtensionMessage ef2 = 1001;
	E_ExtensionMessage_Ef2 = &file_regtest_regtest_proto_extTypes[2]
	// optional string ef3 = 1002;
	E_ExtensionMessage_NestedExtension_Ef3 = &file_regtest_regtest_proto_extTypes[3]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional regtest.BaseMessage base = 56789;
	E_Base = &file_regtest_regtest_proto_extTypes[1]
)

var File_regtest_regtest_proto protoreflect.FileDescriptor

var file_regtest_regtest_proto_rawDesc = []byte{
	0x0a, 0x15, 0x72, 0x65, 0x67, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x72, 0x65, 0x67, 0x74, 0x65, 0x73,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x72, 0x65, 0x67, 0x74, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a,
	0x0b, 0x42, 0x61, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x62, 0x66, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x62, 0x66, 0x31, 0x2a, 0x09,
	0x08, 0xe8, 0x07, 0x10, 0x80, 0x80, 0x80, 0x80, 0x02, 0x22, 0xba, 0x01, 0x0a, 0x10, 0x45, 0x78,
	0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x65, 0x6d, 0x66, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x65, 0x6d,
	0x66, 0x31, 0x1a, 0x4e, 0x0a, 0x0f, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x45, 0x78, 0x74, 0x65,
	0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x65, 0x66, 0x31, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x65, 0x66, 0x31, 0x32, 0x27, 0x0a, 0x03, 0x65, 0x66, 0x33,
	0x12, 0x14, 0x2e, 0x72, 0x65, 0x67, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0xea, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65,
	0x66, 0x33, 0x32, 0x42, 0x0a, 0x03, 0x65, 0x66, 0x32, 0x12, 0x14, 0x2e, 0x72, 0x65, 0x67, 0x74,
	0x65, 0x73, 0x74, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0xe9, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x72, 0x65, 0x67, 0x74, 0x65, 0x73, 0x74,
	0x2e, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x03, 0x65, 0x66, 0x32, 0x32, 0x4b, 0x0a, 0x05, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x12,
	0x42, 0x0a, 0x05, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x09, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x03,
	0x3a, 0x01, 0x2a, 0x3a, 0x27, 0x0a, 0x03, 0x65, 0x66, 0x31, 0x12, 0x14, 0x2e, 0x72, 0x65, 0x67,
	0x74, 0x65, 0x73, 0x74, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0xe8, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x66, 0x31, 0x3a, 0x4a, 0x0a, 0x04,
	0x62, 0x61, 0x73, 0x65, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd5, 0xbb, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x72,
	0x65, 0x67, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x42, 0x1b, 0x5a, 0x19, 0x66, 0x6f, 0x78, 0x79,
	0x67, 0x6f, 0x2e, 0x61, 0x74, 0x2f, 0x6a, 0x69, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x79,
}

var (
	file_regtest_regtest_proto_rawDescOnce sync.Once
	file_regtest_regtest_proto_rawDescData = file_regtest_regtest_proto_rawDesc
)

func file_regtest_regtest_proto_rawDescGZIP() []byte {
	file_regtest_regtest_proto_rawDescOnce.Do(func() {
		file_regtest_regtest_proto_rawDescData = protoimpl.X.CompressGZIP(file_regtest_regtest_proto_rawDescData)
	})
	return file_regtest_regtest_proto_rawDescData
}

var file_regtest_regtest_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_regtest_regtest_proto_goTypes = []interface{}{
	(*BaseMessage)(nil),                      // 0: regtest.BaseMessage
	(*ExtensionMessage)(nil),                 // 1: regtest.ExtensionMessage
	(*ExtensionMessage_NestedExtension)(nil), // 2: regtest.ExtensionMessage.NestedExtension
	(*descriptorpb.MethodOptions)(nil),       // 3: google.protobuf.MethodOptions
	(*emptypb.Empty)(nil),                    // 4: google.protobuf.Empty
}
var file_regtest_regtest_proto_depIdxs = []int32{
	0, // 0: regtest.ef1:extendee -> regtest.BaseMessage
	3, // 1: regtest.base:extendee -> google.protobuf.MethodOptions
	0, // 2: regtest.ExtensionMessage.ef2:extendee -> regtest.BaseMessage
	0, // 3: regtest.ExtensionMessage.NestedExtension.ef3:extendee -> regtest.BaseMessage
	0, // 4: regtest.base:type_name -> regtest.BaseMessage
	1, // 5: regtest.ExtensionMessage.ef2:type_name -> regtest.ExtensionMessage
	4, // 6: regtest.Dummy.Dummy:input_type -> google.protobuf.Empty
	4, // 7: regtest.Dummy.Dummy:output_type -> google.protobuf.Empty
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	4, // [4:6] is the sub-list for extension type_name
	0, // [0:4] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_regtest_regtest_proto_init() }
func file_regtest_regtest_proto_init() {
	if File_regtest_regtest_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_regtest_regtest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			case 3:
				return &v.extensionFields
			default:
				return nil
			}
		}
		file_regtest_regtest_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtensionMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_regtest_regtest_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtensionMessage_NestedExtension); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_regtest_regtest_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 4,
			NumServices:   1,
		},
		GoTypes:           file_regtest_regtest_proto_goTypes,
		DependencyIndexes: file_regtest_regtest_proto_depIdxs,
		MessageInfos:      file_regtest_regtest_proto_msgTypes,
		ExtensionInfos:    file_regtest_regtest_proto_extTypes,
	}.Build()
	File_regtest_regtest_proto = out.File
	file_regtest_regtest_proto_rawDesc = nil
	file_regtest_regtest_proto_goTypes = nil
	file_regtest_regtest_proto_depIdxs = nil
}
